-- 1. UTENTI
CREATE TABLE USERS
(
    ID            BIGSERIAL PRIMARY KEY,
    EMAIL         VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH TEXT                NOT NULL,
    CREATED_AT    TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX users_email_unique ON users (email);

-- 2. CONTI (Banca, Contanti, Carta)
CREATE TABLE ACCOUNTS
(
    ID              BIGSERIAL PRIMARY KEY,
    USER_ID         BIGINT       NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    NAME            VARCHAR(100) NOT NULL,
    CURRENCY        CHAR(3)      NOT NULL,
    INITIAL_BALANCE BIGINT       NOT NULL DEFAULT 0, -- Importo in centesimi
    UNIQUE (USER_ID, NAME)
);

-- 3. CATEGORIE (Il "Perché")
CREATE TABLE CATEGORY
(
    ID      BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT       NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    NAME    VARCHAR(100) NOT NULL,
    TYPE    VARCHAR(10)  NOT NULL CHECK (TYPE IN ('INCOME', 'EXPENSE', 'TRANSFER')),
    UNIQUE (USER_ID, NAME, TYPE)
);

-- 5. TRANSAZIONI (La testata dell'evento)
CREATE TABLE TRANSACTIONS
(
    ID          BIGSERIAL PRIMARY KEY,
    USER_ID     BIGINT NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    OCCURRED_AT DATE   NOT NULL
);

-- 6. MOVIMENTI (Le righe contabili effettive)
CREATE TABLE TRANSACTION_ENTRIES
(
    ID             BIGSERIAL PRIMARY KEY,
    TRANSACTION_ID BIGINT NOT NULL REFERENCES TRANSACTIONS (ID) ON DELETE CASCADE,
    ACCOUNT_ID     BIGINT NOT NULL REFERENCES ACCOUNTS (ID) ON DELETE CASCADE,
    CATEGORY_ID    BIGINT REFERENCES CATEGORY (ID) ON DELETE SET NULL,
    AMOUNT         BIGINT NOT NULL, -- Importo in centesimi
    DESCRIPTION    TEXT
);
